### ISSUE TITLE
Can't find temp file

### ISSUE THREAD

**Issue by ivobrands** [Garefild/PoeditSmarty#3]
see error
wo 17 feb 11:46:52 2016: /Applications/Poedit.app/Contents/PlugIns/GettextTools.bundle/Contents/MacOS/bin/msgcat: fout bij openen van '/var/folders/h1/k5_yjxx53w9_q9fkycknglyh0000gq/T/poeditpM4WLF/1extracted.pot' voor lezen: No such file or directory

its saying erro with opening file ... for reading: No such file or directory. If i use poeditSmarty in terminal it works so..
See below for my setup.
![schermafbeelding 2016-02-17 om 12 30 56](https://cloud.githubusercontent.com/assets/14000063/13108271/53915078-d572-11e5-9a5b-5e554477ce41.png)

**Comment by Garefild** [comment]
Okay, I want you to some things.
1. Which Mac system you have?
2. I want to add -d at the end of the command (This will create a log file)

And send me the log file.

**Comment by ivobrands** [comment]
Thanks for the response, 

I'm currectly on OS X El Captain version 10.11.2.
The files .po and .mo are created but empty.
I'm sorry but the log file is in Dutch...

<img width="849" alt="schermafbeelding 2016-02-18 om 13 39 39" src="https://cloud.githubusercontent.com/assets/14000063/13143571/1b35d64e-d645-11e5-8fd2-72fbbb24003f.png">
[log.txt](https://github.com/Garefild/PoeditSmarty/files/136193/log.txt)

**Comment by Garefild** [comment]
Sorry it’s taken me so long, 

Poedit log files do not bring me the information I needed.
When you add the argument "-d" created temporary files folder named "PoeditSmarty".
And this folder has the log files.

this is the path to the log folder: $TMPDIR/PoeditSmarty/log/
example Filename "11022016053137.log"

in your case: var/folders/h1/k5_yjxx53w9_q9fkycknglyh0000gq/T/PoeditSmarty/log/
send me all the log files.

Anyway, I'll run it on mac and check.
And I will release an update ..

Anyway sorry for my poor English.
Feel free to correct me.

**Comment by ivobrands** [comment]
well i checked the logs. The only thing it says is that parameter c is missing? but i included that parameter in the line for the command. well here is the log file.
<img width="510" alt="schermafbeelding 2016-02-22 om 10 31 29" src="https://cloud.githubusercontent.com/assets/14000063/13214406/c5d396f6-d94f-11e5-87fd-405840a857ee.png">
(changed log file extension to txt, else not possible to send it)

[22022016102925.txt](https://github.com/Garefild/PoeditSmarty/files/140352/22022016102925.txt)

**Comment by Garefild** [comment]
Try this: PoeditSmarty.jar -o %O -c %C -k %K -f %F -d
This should solve the problem, in any case, 
I will release an expanded version with support for Mac.

**Comment by ivobrands** [comment]
I tried this command but same error..
When i look at the map /var/folders/h1/k5_yjxx53w9_q9fkycknglyh0000gq/T/poeditFrrB41/0extracted.pot' i can see the map 'poeditFrrB41' very shortly. maybe u have a idea why its deleted after 1 second? thats the reason it can not be found.

**Comment by ivobrands** [comment]
Hello Garefild,

After this problem i got some more questions for you.
Currently using gettext and smarty in a big project for translation. 
To use this i need a fully operational poeditSmarty to keep the po files and ID's in smarty templates synchronously. So i have a few questions,

Is it possible to add function to read variables from the {t} tags? and so the {t} tags if there are variables?
Is it possible to add function to read multiple lines in code? so if opening tag is on rule 1 and closing on rule 3, that he still gets the whole string between the t tags?
Is it possible to add function that can read multiple {t} tags on one rule?
and last see problem above.

Hopefully u can give me some more information.
If u say u don't have time for this, can u make this project open-source so we can make it ourself? If not, we can negotiate about a compensation for your work.

Thanks!
You can also mail me,
ivo@uitzendbureau.nl

**Comment by Garefild** [comment]
fix
