### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by krzysztof-kabala** [Garefild/PoeditSmarty#4]
> 08:50:56: Exception in thread "main" java.lang.NullPointerException
> 08:50:56:     at Poedit.PoeditLogger.warning(PoeditLogger.java:169)
> 08:50:56:     at Poedit.PoeditLogger.<init>(PoeditLogger.java:117)
> 08:50:56:     at PoeditMain.main(PoeditMain.java:50)

POEdit configuration:

> java -jar "/PoeditSmarty-master/java/PoeditSmarty.jar"  -o %O -c %C -k %K -f %F

I dont know why `PoeditLogger.java:169` runs `this.fileHandler.flush();` without `-d` param

**Comment by Garefild** [comment]
fix :)
