### ISSUE TITLE
Unable to open file in windows 10 "temp" folder

### ISSUE THREAD

**Issue by FarUniverse** [Garefild/PoeditSmarty#7]
Hello!
Everything is configured according to the instructions.
Poedit vers. 2.2 (5561) and runs from administrator just in case.
When I click "update from source code", I get error:
Unable to open the file 'C: \ Users \ Nika \ AppData \ Local \ Temp \ poe4CBE.tmp \ legacy_Smarty_extracted.pot' (Error 2: The specified file could not be found.)
When I watch "Temp" folder, I see, that needed subfolder is quickly creataed and then immediatly erased.
Antivirus is switched off temporarily - there is no affect as well.
I don`t know what the matter...

**Comment by Garefild** [comment]
Is this still relevant ?
